package com.cb.yash.Exception.task7;

public class Test7 {
    public static void main(String[] args) {
        ChainedException.chained();
    }
}
